services:
  mysql:
    image: mysql:8.0
    container_name: clean-architecture-mysql
    environment:
      MYSQL_DATABASE: clean_architecture
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
